name: Run linting and tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  backseat-driver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Backseat Driver on this repository
        uses: kostaleonard/backseat-driver-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          filenames: '**/*.py'
          fail-under: C
